CROSS   := x86_64-elf-
CC      := $(CROSS)gcc
LD      := $(CROSS)ld
AS      := nasm

CFLAGS  := -std=gnu11 -ffreestanding -fno-stack-protector -fno-pic -m64 -O2 -Wall -Wextra
LDFLAGS := -T linker.ld

BUILD   := build
ISO     := $(BUILD)/iso_root
KERNEL  := $(BUILD)/kernel.elf
ISOFILE := $(BUILD)/myos.iso

OBJS := \
	$(BUILD)/boot.o \
	$(BUILD)/kernel.o

all: $(ISOFILE)

$(BUILD):
	mkdir -p $(BUILD)
	mkdir -p $(ISO)/boot
	mkdir -p $(ISO)/boot/limine

$(BUILD)/boot.o: arch/x86_64/boot.asm | $(BUILD)
	$(AS) -f elf64 arch/x86_64/boot.asm -o $@

$(BUILD)/kernel.o: kernel/kernel.c | $(BUILD)
	$(CC) $(CFLAGS) -c kernel/kernel.c -o $@

$(KERNEL): $(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) -o $(KERNEL)

$(ISOFILE): $(KERNEL) limine.conf | $(BUILD)
	cp $(KERNEL) $(ISO)/boot/kernel.elf
	cp limine.conf $(ISO)/boot/limine/limine.conf
	cp limine/limine-bios.sys $(ISO)/boot/limine/
	cp limine/limine-bios-cd.bin $(ISO)/boot/limine/
	cp limine/limine-uefi-cd.bin $(ISO)/boot/limine/

	xorriso -as mkisofs \
		-b boot/limine/limine-bios-cd.bin \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		--efi-boot boot/limine/limine-uefi-cd.bin \
		-efi-boot-part --efi-boot-image --protective-msdos-label \
		$(ISO) -o $(ISOFILE)

	./limine/limine bios-install $(ISOFILE)

run: $(ISOFILE)
	qemu-system-x86_64 \
		-cdrom $(ISOFILE) \
		-serial stdio \
		-m 256M

clean:
	rm -rf $(BUILD)

.PHONY: all run clean